### PR TITLE
Implement Bookmark Functionality for Rendering Bookmarked Topics

### LINKED ISSUE #16: US #2 Update Page to Filter Bookmarks
## Description

Update frontend so a user can see only bookmarked posts. This can be done with a new filtering option, or an entirely separate page for bookmarked posts. This will also require client-side implementations for handling state changes, and calling the new bookmark API.

## Dependencies

- Specification document for implementation. 
- Bookmark API is working.

## Acceptance Criteria

Frontend is manually tested.

## Effort Estimate 

**16 hours**

### PR DESCRIPTION
**Pull request by bestpantusen**
This PR adds a new function handleBookmarks() in category.js to implement the bookmark/unbookmark functionality for topics in the category view. Added functionality to manage bookmarked topics by attaching click event listeners, sending POST/DELETE requests, and toggling the bookmark state with success/error notifications. Users can now bookmark or unbookmark a topic, allowing easy bookmarking directly from the category page.

Path: public/src/client/category.js

Resolves: #16

### CODE REVIEW

**Review by zhanwen22 — COMMENTED** [review]
I feel that the try/catch is a good structure to have in this code. Overall should be helpful for our code repo.

**Review by wandrew004 — APPROVED** [review]
LGTM

**Comment by JordanFnsg** [comment]
I agree with Wenna that try/catch is good. Additionally, I think its good to add the delete bookmark if user clicks on a saved topic.

**Comment by bestpantusen** [comment]
Tests failing unrelated to my changes

**Pull request merged**
