### PR TITLE
add post and update for bookmark

### LINKED ISSUE #12: US #2 Add logic for POST request
## Description

Add logic for POST request to the backend API. Also create corresponding unit tests.

## Dependencies

- Specification document for implementation. 
- Bookmark API routes are created and API documentation exists.

## Acceptance Criteria

API logic is created and unit tests are passing.

## Effort Estimate 

**12 hours**

### PR DESCRIPTION
**Pull request by wandrew004**
Resolves #12 

These changes add the API Post and Update logic for the bookmark feature as part of US#2. Writing test cases is part of a different task.

The file path is src/topics/bookmarks.js.

### CODE REVIEW

**Comment by bestpantusen** [comment]
This looks good. Great job.

**Review by bestpantusen — COMMENTED** [review]
This looks good. Great job.

**Comment by zzzannie** [comment]
looks good to me, great effort and good use of Math

**Comment by wandrew004** [comment]
Test failing unrelated to my changes

**Pull request merged**
